const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const TOGGLE_FROM_GROUP = 'TOGGLE_FROM_GROUP'
//User
const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';

const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL'
//User
const USER_CHANGING_PASSWORD_REQUEST = 'USER_CHANGING_PASSWORD_REQUEST';
const USER_CHANGING_PASSWORD_SUCCESS = 'USER_CHANGING_PASSWORD_SUCCESS';
const USER_CHANGING_PASSWORD_FAIL = 'USER_CHANGING_PASSWORD_FAIL';

// tao const group
const GET_LIST_GROUP_REUEST = 'GET_LIST_GROUP_REUEST'
const GET_LIST_GROUP_SUCCESS = 'GET_LIST_GROUP_SUCCESS'
const GET_LIST_GROUP_FAIL = 'GET_LIST_GROUP_FAIL'

// Delate group
const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST'
const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL'

// Update group
const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST'
const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'

// Create group
const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST'
const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL'
export {

    TOGGLE_SIDEBAR,
    TOGGLE_FROM_GROUP,

    //Signin
    USER_SIGNIN_REQUEST,
    USER_SIGNIN_SUCCESS,
    USER_SIGNIN_FAIL,

    //Signup
    USER_SIGNUP_REQUEST,
    USER_SIGNUP_SUCCESS,
    USER_SIGNUP_FAIL,

    //Get User info
    GET_USER_INFO_REQUEST,
    GET_USER_INFO_SUCCESS,
    GET_USER_INFO_FAIL,

    //Update User
    UPDATE_USER_INFO_REQUEST,
    UPDATE_USER_INFO_SUCCESS,
    UPDATE_USER_INFO_FAIL,

    //Change Password
    USER_CHANGING_PASSWORD_REQUEST,
    USER_CHANGING_PASSWORD_SUCCESS,
    USER_CHANGING_PASSWORD_FAIL,

    //Get ListGroup
    GET_LIST_GROUP_REUEST,
    GET_LIST_GROUP_SUCCESS,
    GET_LIST_GROUP_FAIL,

    // Delete group
    DELETE_GROUP_REQUEST,
    DELETE_GROUP_SUCCESS,
    DELETE_GROUP_FAIL,

    // Udate group
    UPDATE_GROUP_REQUEST,
    UPDATE_GROUP_SUCCESS,
    UPDATE_GROUP_FAIL,

    // Create group
    CREATE_GROUP_REQUEST,
    CREATE_GROUP_SUCCESS,
    CREATE_GROUP_FAIL,


}